<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Applied Retail Forecasting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a></li>
  <li><a href="#exploratory-data-analaysis-eda" id="toc-exploratory-data-analaysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analaysis-eda"><span class="header-section-number">3</span> Exploratory Data Analaysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#trend-seasonality-and-structural-features" id="toc-trend-seasonality-and-structural-features" class="nav-link" data-scroll-target="#trend-seasonality-and-structural-features"><span class="header-section-number">3.1</span> Trend, seasonality, and structural features</a></li>
  <li><a href="#data-transformation-and-decomposition" id="toc-data-transformation-and-decomposition" class="nav-link" data-scroll-target="#data-transformation-and-decomposition"><span class="header-section-number">3.2</span> Data transformation and decomposition</a>
  <ul class="collapse">
  <li><a href="#variance-stabilisation-using-the-boxcox-transformation" id="toc-variance-stabilisation-using-the-boxcox-transformation" class="nav-link" data-scroll-target="#variance-stabilisation-using-the-boxcox-transformation"><span class="header-section-number">3.2.1</span> Variance stabilisation using the Box–Cox transformation</a></li>
  <li><a href="#seasonal-trend-decomposition-using-stl" id="toc-seasonal-trend-decomposition-using-stl" class="nav-link" data-scroll-target="#seasonal-trend-decomposition-using-stl"><span class="header-section-number">3.2.2</span> Seasonal-trend decomposition using STL</a></li>
  <li><a href="#stationarity-and-differencing" id="toc-stationarity-and-differencing" class="nav-link" data-scroll-target="#stationarity-and-differencing"><span class="header-section-number">3.2.3</span> Stationarity and differencing</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-identification-and-selection" id="toc-model-identification-and-selection" class="nav-link" data-scroll-target="#model-identification-and-selection"><span class="header-section-number">4</span> Model Identification and Selection</a>
  <ul class="collapse">
  <li><a href="#candidate-model-specification" id="toc-candidate-model-specification" class="nav-link" data-scroll-target="#candidate-model-specification"><span class="header-section-number">4.1</span> Candidate model specification</a>
  <ul class="collapse">
  <li><a href="#exponential-smoothing-ets-models" id="toc-exponential-smoothing-ets-models" class="nav-link" data-scroll-target="#exponential-smoothing-ets-models"><span class="header-section-number">4.1.1</span> Exponential smoothing (ETS) models</a></li>
  <li><a href="#arima-model-identification" id="toc-arima-model-identification" class="nav-link" data-scroll-target="#arima-model-identification"><span class="header-section-number">4.1.2</span> ARIMA model identification</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-comparison-using-information-criteria" id="toc-model-comparison-using-information-criteria" class="nav-link" data-scroll-target="#model-comparison-using-information-criteria"><span class="header-section-number">5</span> Model comparison using information criteria</a>
  <ul class="collapse">
  <li><a href="#ets-model-comparison" id="toc-ets-model-comparison" class="nav-link" data-scroll-target="#ets-model-comparison"><span class="header-section-number">5.1</span> ETS model comparison</a></li>
  <li><a href="#arima-model-comparison" id="toc-arima-model-comparison" class="nav-link" data-scroll-target="#arima-model-comparison"><span class="header-section-number">5.2</span> ARIMA model comparison</a></li>
  <li><a href="#test-set-evaluation-and-final-model-selection" id="toc-test-set-evaluation-and-final-model-selection" class="nav-link" data-scroll-target="#test-set-evaluation-and-final-model-selection"><span class="header-section-number">5.3</span> Test-set evaluation and final model selection</a></li>
  </ul></li>
  <li><a href="#model-diagnostics-and-forecasting" id="toc-model-diagnostics-and-forecasting" class="nav-link" data-scroll-target="#model-diagnostics-and-forecasting"><span class="header-section-number">6</span> Model diagnostics and forecasting</a>
  <ul class="collapse">
  <li><a href="#parameter-estimates" id="toc-parameter-estimates" class="nav-link" data-scroll-target="#parameter-estimates"><span class="header-section-number">6.1</span> Parameter estimates</a></li>
  <li><a href="#residual-diagnostics" id="toc-residual-diagnostics" class="nav-link" data-scroll-target="#residual-diagnostics"><span class="header-section-number">6.2</span> Residual diagnostics</a></li>
  <li><a href="#forecasts-and-prediction-intervals" id="toc-forecasts-and-prediction-intervals" class="nav-link" data-scroll-target="#forecasts-and-prediction-intervals"><span class="header-section-number">6.3</span> Forecasts and prediction intervals</a></li>
  <li><a href="#test-set-comparison" id="toc-test-set-comparison" class="nav-link" data-scroll-target="#test-set-comparison"><span class="header-section-number">6.4</span> Test-set comparison</a></li>
  <li><a href="#final-forecasts-using-full-data" id="toc-final-forecasts-using-full-data" class="nav-link" data-scroll-target="#final-forecasts-using-full-data"><span class="header-section-number">6.5</span> Final forecasts using full data</a></li>
  </ul></li>
  <li><a href="#forecast-validation-using-updated-abs-data" id="toc-forecast-validation-using-updated-abs-data" class="nav-link" data-scroll-target="#forecast-validation-using-updated-abs-data"><span class="header-section-number">7</span> Forecast validation using updated ABS data</a></li>
  <li><a href="#model-strengths-limitations-and-operational-use" id="toc-model-strengths-limitations-and-operational-use" class="nav-link" data-scroll-target="#model-strengths-limitations-and-operational-use"><span class="header-section-number">8</span> Model strengths, limitations, and operational use</a>
  <ul class="collapse">
  <li><a href="#strengths-and-limitations-of-the-selected-models" id="toc-strengths-and-limitations-of-the-selected-models" class="nav-link" data-scroll-target="#strengths-and-limitations-of-the-selected-models"><span class="header-section-number">8.1</span> Strengths and limitations of the selected models</a></li>
  <li><a href="#forecasting-workflow-in-practice" id="toc-forecasting-workflow-in-practice" class="nav-link" data-scroll-target="#forecasting-workflow-in-practice"><span class="header-section-number">8.2</span> Forecasting workflow in practice</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Applied Retail Forecasting</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>This project applies classical time series forecasting techniques to Australian retail turnover data, with a focus on furniture and household goods retailing in the Northern Territory of Australia. Using monthly data published by the Australian Bureau of Statistics, the analysis aims to understand the underlying structure of the series and assess how different forecasting approaches perform in practice.</p>
<p>The workflow follows a standard applied forecasting process. The data are first explored to identify trends, seasonality, and structural changes, including the impact of major economic events such as COVID-19. Variance-stabilising transformations and decomposition techniques are then used to better understand the series before fitting and evaluating models.</p>
<p>Two model families are considered: Exponential Smoothing State Space (ETS) models and Seasonal ARIMA models. Model selection is guided by a combination of information criteria, residual diagnostics, and out-of-sample performance using a 24-month test set. Forecast accuracy is further assessed by comparing model predictions to subsequently released ABS data.</p>
<p>The goal of this project is not only to produce forecasts, but to demonstrate a transparent and defensible forecasting workflow, highlighting the trade-offs between model interpretability, stability, and responsiveness when applied to real-world economic data.</p>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<p>This analysis uses monthly retail turnover data from the Australian Bureau of Statistics (ABS), Retail Trade, Table 11.</p>
<p>The series represents turnover for furniture, floor coverings, houseware and textile goods retailing in the Northern Territory of Australia, measured in millions of Australian dollars. The data span April 1988 to December 2022 and are observed at a monthly frequency. A small sample of the dataset is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="uvuorbfike" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#uvuorbfike table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#uvuorbfike thead, #uvuorbfike tbody, #uvuorbfike tfoot, #uvuorbfike tr, #uvuorbfike td, #uvuorbfike th {
  border-style: none;
}

#uvuorbfike p {
  margin: 0;
  padding: 0;
}

#uvuorbfike .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uvuorbfike .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#uvuorbfike .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uvuorbfike .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uvuorbfike .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uvuorbfike .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uvuorbfike .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uvuorbfike .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uvuorbfike .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uvuorbfike .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uvuorbfike .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uvuorbfike .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uvuorbfike .gt_spanner_row {
  border-bottom-style: hidden;
}

#uvuorbfike .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#uvuorbfike .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uvuorbfike .gt_from_md > :first-child {
  margin-top: 0;
}

#uvuorbfike .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uvuorbfike .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uvuorbfike .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#uvuorbfike .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#uvuorbfike .gt_row_group_first td {
  border-top-width: 2px;
}

#uvuorbfike .gt_row_group_first th {
  border-top-width: 2px;
}

#uvuorbfike .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uvuorbfike .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#uvuorbfike .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#uvuorbfike .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uvuorbfike .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uvuorbfike .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uvuorbfike .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#uvuorbfike .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uvuorbfike .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uvuorbfike .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uvuorbfike .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uvuorbfike .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uvuorbfike .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uvuorbfike .gt_left {
  text-align: left;
}

#uvuorbfike .gt_center {
  text-align: center;
}

#uvuorbfike .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uvuorbfike .gt_font_normal {
  font-weight: normal;
}

#uvuorbfike .gt_font_bold {
  font-weight: bold;
}

#uvuorbfike .gt_font_italic {
  font-style: italic;
}

#uvuorbfike .gt_super {
  font-size: 65%;
}

#uvuorbfike .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#uvuorbfike .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#uvuorbfike .gt_indent_1 {
  text-indent: 5px;
}

#uvuorbfike .gt_indent_2 {
  text-indent: 10px;
}

#uvuorbfike .gt_indent_3 {
  text-indent: 15px;
}

#uvuorbfike .gt_indent_4 {
  text-indent: 20px;
}

#uvuorbfike .gt_indent_5 {
  text-indent: 25px;
}

#uvuorbfike .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#uvuorbfike div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="state" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">state</th>
<th id="industry" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">industry</th>
<th id="series_id" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">series_id</th>
<th id="month" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">month</th>
<th id="turnover" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">turnover</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 Apr</td>
<td class="gt_row gt_right" headers="turnover">1.9</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 May</td>
<td class="gt_row gt_right" headers="turnover">2.3</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 Jun</td>
<td class="gt_row gt_right" headers="turnover">2.1</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 Jul</td>
<td class="gt_row gt_right" headers="turnover">1.9</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 Aug</td>
<td class="gt_row gt_right" headers="turnover">2.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="state">Northern Territory</td>
<td class="gt_row gt_left" headers="industry">Furniture, floor coverings, houseware and textile goods retailing</td>
<td class="gt_row gt_left" headers="series_id">A3349526J</td>
<td class="gt_row gt_center" headers="month">1988 Sep</td>
<td class="gt_row gt_right" headers="turnover">1.9</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="exploratory-data-analaysis-eda" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Exploratory Data Analaysis (EDA)</h1>
<p>Exploratory analysis is used to understand the overall structure of the retail turnover series before any modeling is performed. This includes examining long-term trends, seasonal patterns, and changes in variability over time, as well as identifying potential structural breaks linked to broader economic conditions.</p>
<p>A set of time series visualizations are used to assess these features. These plots help determine whether the series exhibits trend and seasonality, whether variance appears constant over time, and whether there are periods of unusually high or low volatility. Particular attention is given to changes around major events such as the mining boom period and the COVID-19 pandemic, both of which are expected to have influenced retail behaviour in the Northern Territory.</p>
<p>The insights from this exploratory stage inform later decisions around transformation, decomposition, and model selection.</p>
<section id="trend-seasonality-and-structural-features" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="trend-seasonality-and-structural-features"><span class="header-section-number">3.1</span> Trend, seasonality, and structural features</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot1-1.png" id="fig-plot1" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot2-1.png" id="fig-plot2" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot3" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot3-1.png" id="fig-plot3" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<p>The dataset captures monthly retail turnover for furniture, floor coverings, houseware and textile goods retailing in the Northern Territory, spanning April 1988 to December 2022.</p>
<p>The time series plot in <a href="#fig-plot1" class="quarto-xref">Figure&nbsp;1</a> shows a clear upward long-term trend, indicating sustained growth in retail turnover over the sample period. Seasonal behaviour is also evident, with fluctuations that increase in magnitude as the level of the series rises, suggesting multiplicative seasonality. A pronounced increase in turnover is observed between approximately 2007 and 2009, which likely reflects the effects of the Northern Territory mining boom during that period. Following this, turnover declines sharply post-2010, potentially linked to the global financial crisis and the subsequent slowdown in mining-related economic activity.</p>
<p>In the years leading up to 2020, turnover appears relatively subdued before rising again during and after the COVID-19 period. While many industries experienced contraction during this time, the increase observed here may reflect shifts in household behaviour, with greater emphasis on home-related spending as lifestyles adjusted. Given the broad scope of this retail category, multiple overlapping factors are likely influencing the observed dynamics.</p>
<p>The seasonal plot in <a href="#fig-plot2" class="quarto-xref">Figure&nbsp;2</a> highlights strong and consistent seasonal patterns across years. Turnover tends to peak in June and December, while lower values are commonly observed around February and April. The regular repetition of these patterns supports the presence of true seasonality rather than irregular cyclical effects. Although the exact drivers are not directly observed in the data, these patterns may be associated with factors such as end-of-financial-year spending, holiday periods, and seasonal changes in consumer behaviour.</p>
<p>The subseries plot in <a href="#fig-plot3" class="quarto-xref">Figure&nbsp;3</a> further reinforces these findings by displaying monthly behaviour across the full time span. Each month exhibits a distinct seasonal profile, while also reflecting the broader upward movement in turnover over time. June and December consistently record higher average turnover, whereas February and April remain comparatively weaker months. The horizontal reference lines representing monthly means make these differences particularly clear.</p>
<p>One notable feature in the subseries plot is an unusually high turnover value observed in July around 2007. This may represent a genuine economic anomaly linked to exceptional conditions during that period, although the possibility of a data irregularity cannot be ruled out. Overall, the exploratory analysis confirms the presence of trend, seasonality, and changing variance, all of which are important considerations for subsequent transformation and model selection.</p>
</section>
<section id="data-transformation-and-decomposition" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="data-transformation-and-decomposition"><span class="header-section-number">3.2</span> Data transformation and decomposition</h2>
<p>This section focuses on preparing the series for modelling by addressing changing variance and separating the underlying components of the time series. These steps help ensure that subsequent models are applied to data that are more stable and interpretable.</p>
<section id="variance-stabilisation-using-the-boxcox-transformation" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="variance-stabilisation-using-the-boxcox-transformation"><span class="header-section-number">3.2.1</span> Variance stabilisation using the Box–Cox transformation</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot4" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot4-1.png" id="fig-plot4" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
</div>
</div>
<p>To stabilize the variance of the series and address heteroskedasticity, a Box–Cox transformation is applied to the retail turnover data. The transformation parameter λ is selected using the Guerrero method, which chooses the value that minimizes variability across seasonal subseries. Applying this procedure yields an estimated λ value of 0.242.</p>
<p>Figure <a href="#fig-plot4" class="quarto-xref">Figure&nbsp;4</a> compares the Box–Cox transformation using the Guerrero-estimated value with a log transformation, corresponding to λ = 0. Both transformations reduce variance instability relative to the original series; however, the log-transformed series exhibits slightly tighter peaks and troughs, indicating more consistent variance across seasonal periods. The estimated value being close to zero suggests that a log transformation is sufficient in practice.</p>
<p>Overall, comparison with the original series in <a href="#fig-plot1" class="quarto-xref">Figure&nbsp;1</a> indicates that the transformation is effective in achieving approximate variance stability, making the data more suitable for subsequent decomposition and time series modelling.</p>
</section>
<section id="seasonal-trend-decomposition-using-stl" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="seasonal-trend-decomposition-using-stl"><span class="header-section-number">3.2.2</span> Seasonal-trend decomposition using STL</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot5" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot5-1.png" id="fig-plot5" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
</div>
</div>
<p>Following variance stabilization, the transformed series is decomposed using STL to separate the trend, seasonal, and remainder components. This helps assess whether seasonality is stable over time and whether any meaningful structure remains unexplained.</p>
<p>Because the series spans multiple decades, STL parameters are adjusted rather than relying on defaults. The seasonal window is set to 13 to allow the seasonal component to vary smoothly while still reflecting an annual cycle, which is appropriate for monthly retail data where recurring patterns such as end-of-financial-year and holiday periods are expected. The trend window is set to 25 to capture medium-term movements (roughly two years), allowing the trend component to reflect gradual shifts associated with changing economic conditions in the Northern Territory.</p>
<p>Given the presence of irregular spikes and sharp movements, particularly between 2007 and 2022, <code>robust = TRUE</code> is used to reduce the influence of extreme observations on the estimated components. With these settings, the decomposition in <a href="#fig-plot5" class="quarto-xref">Figure&nbsp;5</a> shows a well-defined long-term trend, a stable seasonal pattern, and a remainder that appears largely noise-like, suggesting that the major structure of the series has been captured.</p>
<p>Overall, the STL decomposition confirms that this turnover series is characterized by a persistent long-run trend and consistent seasonal variation year to year, supporting the use of seasonal forecasting models in later sections.</p>
</section>
<section id="stationarity-and-differencing" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="stationarity-and-differencing"><span class="header-section-number">3.2.3</span> Stationarity and differencing</h3>
<div id="tbl-table1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  kpss_stat kpss_pvalue
      &lt;dbl&gt;       &lt;dbl&gt;
1      5.46        0.01</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  nsdiffs
    &lt;int&gt;
1       1</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  ndiffs
   &lt;int&gt;
1      1</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table4" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-table4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  kpss_stat kpss_pvalue
      &lt;dbl&gt;       &lt;dbl&gt;
1    0.0340         0.1</code></pre>
</div>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot6" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot6-1.png" id="fig-plot6" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot7" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot7-1.png" id="fig-plot7" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7
</figcaption>
</figure>
</div>
</div>
</div>
<p>Before fitting ARIMA models, the series must be made stationary by removing any remaining trend and seasonal structure. Visual inspection of the original series in <a href="#fig-plot1" class="quarto-xref">Figure&nbsp;1</a> confirms the presence of both trend and seasonality, while the Box–Cox transformation applied earlier successfully stabilizes variance, as seen in <a href="#fig-plot4" class="quarto-xref">Figure&nbsp;4</a>.</p>
<p>To formally assess stationarity and guide differencing decisions, a set of unit root tests are applied to the transformed series. The KPSS test results in <a href="#tbl-table1" class="quarto-xref">Table&nbsp;1</a> return a p-value of 0.01, providing evidence against stationarity in the undifferenced series. Automated differencing diagnostics suggest applying one seasonal difference (<a href="#tbl-table2" class="quarto-xref">Table&nbsp;2</a>) and one regular difference (<a href="#tbl-table3" class="quarto-xref">Table&nbsp;3</a>).</p>
<p>After applying both a seasonal difference of order 12 and a first-order difference, the KPSS test is repeated on the fully differenced series. The resulting p-value of 0.1 in <a href="#tbl-table4" class="quarto-xref">Table&nbsp;4</a> indicates that there is no strong evidence against stationarity, suggesting that the differencing strategy has been effective.</p>
<p>This progression is also reflected visually. The seasonally differenced series shown in <a href="#fig-plot6" class="quarto-xref">Figure&nbsp;6</a> no longer exhibits clear seasonal patterns, but still displays some residual structure. Applying an additional first-order difference yields the series in <a href="#fig-plot7" class="quarto-xref">Figure&nbsp;7</a>, which fluctuates around a constant mean with no obvious trend or seasonality, consistent with a stationary process.</p>
<p>Overall, these results indicate that one seasonal difference and one regular difference are sufficient to achieve stationarity, providing an appropriate foundation for ARIMA model identification in the next section.</p>
</section>
</section>
</section>
<section id="model-identification-and-selection" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Model Identification and Selection</h1>
<section id="candidate-model-specification" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="candidate-model-specification"><span class="header-section-number">4.1</span> Candidate model specification</h2>
<section id="exponential-smoothing-ets-models" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="exponential-smoothing-ets-models"><span class="header-section-number">4.1.1</span> Exponential smoothing (ETS) models</h3>
<p>Based on the exploratory analysis, the series exhibits a clear trend, strong seasonality, increasing variance, and occasional sharp movements. These characteristics motivate the use of exponential smoothing models that can accommodate trend damping and multiplicative effects.</p>
<p>A set of candidate ETS models is considered. All models use a damped additive trend to reflect the expectation that long-run growth may flatten over time, particularly given the observed fluctuations in the series. The shortlisted models include:</p>
<ol type="1">
<li>an additive Holt–Winters specification,</li>
<li>a hybrid model with multiplicative errors and additive seasonality,</li>
<li>a fully multiplicative specification,</li>
<li>and an automatically selected ETS model.</li>
</ol>
<p>These candidates allow comparison between different assumptions about how variance and seasonal effects scale with the level of the series.</p>
</section>
<section id="arima-model-identification" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="arima-model-identification"><span class="header-section-number">4.1.2</span> ARIMA model identification</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot8" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot8-1.png" id="fig-plot8" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8
</figcaption>
</figure>
</div>
</div>
</div>
<p>ARIMA model identification is guided by the autocorrelation and partial autocorrelation functions of the transformed and differenced series, shown in <a href="#fig-plot8" class="quarto-xref">Figure&nbsp;8</a>. One regular difference and one seasonal difference are retained, consistent with the stationarity analysis in the previous section, resulting in a baseline structure of (0,1,0)(0,1,0)[12].</p>
<p>Inspection of the ACF suggests the presence of a non-seasonal moving average component at lag 1, while the PACF indicates a potential non-seasonal autoregressive component at lag 2. At the seasonal level, a significant spike at lag 12 in the ACF suggests a seasonal MA(1) term, while spikes at lags 12 and 24 in the PACF indicate a possible seasonal AR(2) structure.</p>
<p>Based on these patterns, two candidate ARIMA specifications are selected: (2,1,0)(2,1,0)[12] and (2,1,0)(0,1,1)[12], alongside an automatically selected ARIMA model.</p>
</section>
</section>
</section>
<section id="model-comparison-using-information-criteria" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Model comparison using information criteria</h1>
<section id="ets-model-comparison" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="ets-model-comparison"><span class="header-section-number">5.1</span> ETS model comparison</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: turnover 
Model: ETS(M,A,M) 
  Smoothing parameters:
    alpha = 0.4742735 
    beta  = 0.0001020771 
    gamma = 0.09602882 

  Initial states:
     l[0]       b[0]     s[0]    s[-1]     s[-2]    s[-3]    s[-4]    s[-5]
 1.972875 0.01933869 1.003071 0.850079 0.8493874 1.127858 1.009289 1.006564
     s[-6]    s[-7]    s[-8]    s[-9]   s[-10]   s[-11]
 0.9638753 1.036554 1.000923 1.164525 1.057154 0.930721

  sigma^2:  0.0073

     AIC     AICc      BIC 
1786.523 1788.155 1854.078 </code></pre>
</div>
</div>
<div id="tbl-table5" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5
</figcaption>
<div aria-describedby="tbl-table5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 9
  .model    sigma2 log_lik   AIC  AICc   BIC   MSE  AMSE    MAE
  &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 ETS_auto 0.00734   -876. 1787. 1788. 1854. 0.289 0.350 0.0648
2 ETS_MAdA 0.00759   -880. 1797. 1798. 1868. 0.309 0.389 0.0658
3 ETS_MAdM 0.00764   -881. 1797. 1799. 1869. 0.290 0.355 0.0652
4 ETS_AAdA 0.311     -936. 1908. 1909. 1979. 0.298 0.372 0.411 </code></pre>
</div>
</div>
</figure>
</div>
<p>The candidate ETS models are fitted to the training data and compared using the Akaike Information Criterion (AIC), with results summarized in <a href="#tbl-table5" class="quarto-xref">Table&nbsp;5</a>. The automatically selected ETS model, ETS(M,A,M), achieves the lowest AIC, indicating the best in-sample fit among the specifications considered.</p>
<p>However, the damped-trend models ETS(M,Ad,A) and ETS(M,Ad,M) perform comparably in terms of AIC, with only marginally higher values. Given their damped trend structure, these models remain plausible alternatives, particularly if long-run growth is expected to slow.</p>
<p>Note: ETS models are fitted to the original turnover series, as exponential smoothing methods natively accommodate trend and seasonality without requiring prior differencing or transformation.</p>
</section>
<section id="arima-model-comparison" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="arima-model-comparison"><span class="header-section-number">5.2</span> ARIMA model comparison</h2>
<div id="tbl-table6" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6
</figcaption>
<div aria-describedby="tbl-table6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A mable: 3 x 2
# Key:     Model name [3]
  `Model name`                    Orders
  &lt;chr&gt;                          &lt;model&gt;
1 model1       &lt;ARIMA(2,1,0)(2,1,0)[12]&gt;
2 model2       &lt;ARIMA(2,1,0)(0,1,1)[12]&gt;
3 auto         &lt;ARIMA(2,1,0)(0,1,1)[12]&gt;</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table7" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7
</figcaption>
<div aria-describedby="tbl-table7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  .model  sigma2 log_lik   AIC  AICc   BIC
  &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 model2 0.00708    395. -781. -781. -766.
2 auto   0.00708    395. -781. -781. -766.
3 model1 0.00817    373. -736. -736. -717.</code></pre>
</div>
</div>
</figure>
</div>
<p>A similar comparison is conducted for the ARIMA candidates. The automatically selected ARIMA model matches the manually specified (2,1,0)(0,1,1)[12] model, as shown in <a href="#tbl-table6" class="quarto-xref">Table&nbsp;6</a>. Both specifications achieve the lowest AIC values in <a href="#tbl-table7" class="quarto-xref">Table&nbsp;7</a>, indicating strong in-sample performance relative to the alternative candidate.</p>
</section>
<section id="test-set-evaluation-and-final-model-selection" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="test-set-evaluation-and-final-model-selection"><span class="header-section-number">5.3</span> Test-set evaluation and final model selection</h2>
<div id="tbl-table8" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8
</figcaption>
<div aria-describedby="tbl-table8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 10
  .model   .type     ME  RMSE   MAE    MPE  MAPE  MASE RMSSE  ACF1
  &lt;chr&gt;    &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 ETS_MAdA Test  -0.672  1.01 0.879  -7.69  9.55   NaN   NaN 0.178
2 ETS_AAdA Test  -0.823  1.12 0.976  -9.40 10.7    NaN   NaN 0.124
3 ETS_auto Test  -0.840  1.13 0.961  -9.23 10.3    NaN   NaN 0.174
4 ETS_MAdM Test  -1.02   1.27 1.08  -11.1  11.6    NaN   NaN 0.164</code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table9" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9
</figcaption>
<div aria-describedby="tbl-table9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
  .model .type    ME  RMSE   MAE   MPE  MAPE  MASE RMSSE   ACF1
  &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 auto   Test  -1.14  1.35  1.16 -12.3  12.4   NaN   NaN 0.0300
2 model2 Test  -1.14  1.35  1.16 -12.3  12.4   NaN   NaN 0.0300
3 model1 Test  -1.46  1.78  1.46 -15.3  15.3   NaN   NaN 0.306 </code></pre>
</div>
</div>
</figure>
</div>
<p>To assess out-of-sample performance, all shortlisted ETS and ARIMA models are evaluated on a 24-month test set. Forecast accuracy metrics for ETS and ARIMA models are reported in <a href="#tbl-table8" class="quarto-xref">Table&nbsp;8</a> and <a href="#tbl-table9" class="quarto-xref">Table&nbsp;9</a>, respectively.</p>
<p>For the ARIMA models, the (2,1,0)(0,1,1)[12] specification achieves both the lowest AIC and the lowest test-set RMSE, and is also selected automatically by the ARIMA procedure. This consistency provides strong support for its selection as the preferred ARIMA model.</p>
<p>For the ETS models, the automatically selected ETS(M,A,M) model achieves the lowest AIC but performs less well on the test set. In contrast, ETS(M,Ad,A) delivers the lowest test-set RMSE among ETS candidates while maintaining a competitive AIC value. Given its superior out-of-sample performance and damped trend structure, ETS(M,Ad,A) is selected as the preferred ETS model.</p>
<p>These two models are carried forward for detailed diagnostics and forecasting in the next section.</p>
</section>
</section>
<section id="model-diagnostics-and-forecasting" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Model diagnostics and forecasting</h1>
<section id="parameter-estimates" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="parameter-estimates"><span class="header-section-number">6.1</span> Parameter estimates</h2>
<div id="tbl-table10" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10
</figcaption>
<div aria-describedby="tbl-table10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>Series: turnover 
Model: ETS(M,Ad,A) 
  Smoothing parameters:
    alpha = 0.4268619 
    beta  = 0.0001428823 
    gamma = 0.09580096 
    phi   = 0.9798006 

  Initial states:
     l[0]       b[0]       s[0]      s[-1]      s[-2]     s[-3]       s[-4]
 1.935965 0.03466882 0.04304406 -0.3569073 -0.4652471 0.3504102 -0.06845108
       s[-5]       s[-6]     s[-7]      s[-8]    s[-9]    s[-10]     s[-11]
 -0.03246525 -0.06927204 0.1164343 0.01381827 0.442839 0.1834115 -0.1576145

  sigma^2:  0.0076

     AIC     AICc      BIC 
1796.565 1798.394 1868.094 </code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-table11" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11
</figcaption>
<div aria-describedby="tbl-table11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>Series: turnover 
Model: ARIMA(2,1,0)(0,1,1)[12] 
Transformation: box_cox(turnover, 0) 

Coefficients:
          ar1      ar2     sma1
      -0.6228  -0.2730  -0.8564
s.e.   0.0494   0.0496   0.0356

sigma^2 estimated as 0.007082:  log likelihood=394.69
AIC=-781.38   AICc=-781.27   BIC=-765.61</code></pre>
</div>
</div>
</figure>
</div>
<p>Table <a href="#tbl-table10" class="quarto-xref">Table&nbsp;10</a> reports the parameter estimates for the selected ETS(M,Ad,A) model. The level smoothing parameter (α = 0.43) indicates that the model places moderate weight on recent observations when updating the series level. The trend smoothing parameter is close to zero, consistent with the use of a damped trend that evolves slowly over time. The seasonal smoothing parameter (γ = 0.096) suggests relatively stable seasonal patterns, with only gradual updating as new data arrive. The damping parameter (ϕ = 0.98) confirms that the trend is expected to persist in the short term but gradually flatten in the long run.</p>
<p>Parameter estimates for the selected ARIMA(2,1,0)(0,1,1)[12] model are shown in <a href="#tbl-table11" class="quarto-xref">Table&nbsp;11</a>. The negative autoregressive coefficients indicate mild mean-reverting behaviour, where deviations tend to be followed by partial corrections. The seasonal moving average term captures strong dependence at the annual lag, reflecting the importance of shocks occurring at the same time in previous years. Together, these parameters indicate a model that responds to both short-term fluctuations and seasonal structure.</p>
</section>
<section id="residual-diagnostics" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="residual-diagnostics"><span class="header-section-number">6.2</span> Residual diagnostics</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_tsresiduals()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_tsresiduals()` instead.</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-plot9" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot9-1.png" id="fig-plot9" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9
</figcaption>
</figure>
</div>
</div>
</div>
<div id="tbl-table12" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12
</figcaption>
<div aria-describedby="tbl-table12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .model   lb_stat lb_pvalue
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 ETS_MAdA    58.5 0.0000212</code></pre>
</div>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot10" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot10-1.png" id="fig-plot10" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10
</figcaption>
</figure>
</div>
</div>
</div>
<div id="tbl-table13" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13
</figcaption>
<div aria-describedby="tbl-table13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .model lb_stat lb_pvalue
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 model2    31.3    0.0686</code></pre>
</div>
</div>
</figure>
</div>
<p>Residual diagnostics are used to assess whether the fitted models have adequately captured the systematic structure in the data. For the ETS model, the residual plots in <a href="#fig-plot9" class="quarto-xref">Figure&nbsp;9</a> show several autocorrelation spikes beyond the 95% confidence bounds. This is supported by the Ljung–Box test results in <a href="#tbl-table12" class="quarto-xref">Table&nbsp;12</a>, which return a very small p-value at lag 24, providing strong evidence against the residuals being white noise. While this suggests that some autocorrelation remains unmodelled, this behaviour is not uncommon for ETS models and does not necessarily preclude good forecasting performance.</p>
<p>In contrast, the residual diagnostics for the ARIMA model in <a href="#fig-plot10" class="quarto-xref">Figure&nbsp;10</a> show no substantial autocorrelation remaining, with only a single spike marginally exceeding the confidence bounds. The Ljung–Box test in <a href="#tbl-table13" class="quarto-xref">Table&nbsp;13</a> returns a p-value of 0.069, indicating no strong evidence of residual autocorrelation. This suggests that the ARIMA model has captured the underlying dependence structure effectively and produces residuals consistent with white noise.</p>
</section>
<section id="forecasts-and-prediction-intervals" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="forecasts-and-prediction-intervals"><span class="header-section-number">6.3</span> Forecasts and prediction intervals</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot11" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot11-1.png" id="fig-plot11" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11
</figcaption>
</figure>
</div>
</div>
</div>
<p>Forecasts from the selected ETS and ARIMA models are shown in <a href="#fig-plot11" class="quarto-xref">Figure&nbsp;11</a>. Both models generate similar short-term forecasts and capture the recurring seasonal pattern in the data. However, differences emerge in their treatment of longer-term uncertainty.</p>
<p>The ETS model produces smoother forecasts with relatively narrow prediction intervals, reflecting its damped trend structure and assumption of stable long-run behaviour. In contrast, the ARIMA model produces wider prediction intervals, indicating greater sensitivity to recent variability and uncertainty in future dynamics. While both forecasts are plausible, the ARIMA model reflects a higher degree of uncertainty, whereas the ETS model provides more conservative and stable projections.</p>
</section>
<section id="test-set-comparison" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="test-set-comparison"><span class="header-section-number">6.4</span> Test-set comparison</h2>
<p>Both the ETS and ARIMA models perform well on the 24-month test set, capturing the underlying seasonal structure and overall movement in retail turnover. However, differences emerge when comparing forecast accuracy and uncertainty.</p>
<p>The ETS(M,Ad,A) model achieves the lowest RMSE on the test set, as shown in <a href="#tbl-table8" class="quarto-xref">Table&nbsp;8</a> and <a href="#tbl-table9" class="quarto-xref">Table&nbsp;9</a>, indicating superior out-of-sample accuracy. Its forecasts are smoother and more stable, reflecting the damped trend structure and assumption of gradual long-run behaviour.</p>
<p>In contrast, the ARIMA(2,1,0)(0,1,1)[12] model achieves a slightly lower in-sample AIC and responds more strongly to recent fluctuations in the data. While this flexibility allows it to adapt quickly to changes, it also results in higher test-set RMSE and wider prediction intervals, indicating greater forecast uncertainty.</p>
<p>Overall, the ETS model provides more stable and reliable forecasts in an out-of-sample setting, while the ARIMA model may be preferable in environments where rapid changes and short-term volatility are of primary interest.</p>
</section>
<section id="final-forecasts-using-full-data" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="final-forecasts-using-full-data"><span class="header-section-number">6.5</span> Final forecasts using full data</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot12" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot12-1.png" id="fig-plot12" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12
</figcaption>
</figure>
</div>
</div>
</div>
<p>To produce final forecasts, both selected models are refitted to the full dataset using the same model structures identified earlier. Parameter estimates are re-estimated, but no changes are made to the model specifications.</p>
<p>Figure <a href="#fig-plot12" class="quarto-xref">Figure&nbsp;12</a> shows two-year ahead forecasts from the refitted ETS and ARIMA models, along with 80% prediction intervals. Both models project a continuation of recent trends and seasonal patterns, while differing in the degree of forecast uncertainty. The ETS forecasts remain relatively smooth and constrained, whereas the ARIMA forecasts allow for a wider range of possible outcomes, reflecting their sensitivity to recent variability.</p>
<p>These final forecasts illustrate how each modelling approach extrapolates beyond the observed data and highlight the trade-off between forecast stability and responsiveness.</p>
</section>
</section>
<section id="forecast-validation-using-updated-abs-data" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Forecast validation using updated ABS data</h1>
<div id="tbl-table14" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-table14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14
</figcaption>
<div aria-describedby="tbl-table14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  .model       RMSE   MAE  MAPE
  &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 final_arima 0.641 0.527  5.16
2 final_ets   0.804 0.572  5.45</code></pre>
</div>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot13" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_files/figure-html/fig-plot13-1.png" id="fig-plot13" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-plot13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13
</figcaption>
</figure>
</div>
</div>
</div>
<p>To evaluate how the selected models perform in a real-world setting, updated retail turnover data are obtained from the Australian Bureau of Statistics (ABS) for the period following the end of the original sample. This allows the forecasts produced in the previous section to be compared against realised values that were not available at the time the models were estimated.</p>
<p>Figure <a href="#fig-plot13" class="quarto-xref">Figure&nbsp;13</a> and the accuracy metrics reported in <a href="#tbl-table14" class="quarto-xref">Table&nbsp;14</a> show that both models capture the underlying seasonal structure reasonably well over the 2023–2024 period. However, the ARIMA model consistently outperforms the ETS model across all reported measures. In particular, the ARIMA model achieves lower RMSE, MAE, and MAPE values (RMSE = 0.641 compared to 0.804 for ETS), indicating superior short-term accuracy during this period.</p>
<p>Visually, the ARIMA forecasts track the observed ABS values more closely, especially during the first half of 2024, where the ETS model tends to underpredict turnover. This suggests that the ARIMA model is better able to adapt to recent volatility and short-term shifts in the series, whereas the ETS model produces smoother and more conservative projections.</p>
<p>These results highlight an important trade-off observed throughout the analysis. While ETS models provide stable and reliable forecasts under relatively smooth conditions, ARIMA models may offer improved performance when the underlying dynamics of the series change more rapidly. In practice, model choice should therefore be guided by the forecasting horizon and the expected stability of the economic environment.</p>
</section>
<section id="model-strengths-limitations-and-operational-use" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Model strengths, limitations, and operational use</h1>
<section id="strengths-and-limitations-of-the-selected-models" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="strengths-and-limitations-of-the-selected-models"><span class="header-section-number">8.1</span> Strengths and limitations of the selected models</h2>
<p>Both the ETS and ARIMA models demonstrate clear strengths when applied to this retail turnover series, but each also has limitations. The ETS model provides a structured and interpretable framework for modelling level, trend, and seasonality. Its forecasts are stable, smooth, and easy to communicate, making it a strong choice when consistency and interpretability are prioritised. However, this same structure can cause the model to respond slowly to sudden changes, particularly during periods of increased volatility or structural shifts.</p>
<p>The ARIMA model, in contrast, is more reactive to recent movements in the data. This responsiveness allowed it to outperform ETS in terms of forecast accuracy when evaluated against realised ABS data for 2023–2024. That said, its forecasts are less smooth and its behaviour can be harder to interpret, especially when multiple autoregressive and moving average components interact. While ARIMA achieved better numerical accuracy in this case, neither model fully captured all short-term fluctuations in the series, reflecting the inherent noise and complexity of retail turnover data.</p>
<p>Overall, the results highlight a key trade-off common in applied forecasting. ETS models offer clarity and stability, while ARIMA models provide flexibility and responsiveness. The “better” model depends on whether the forecasting objective prioritises interpretability or short-term accuracy.</p>
</section>
<section id="forecasting-workflow-in-practice" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="forecasting-workflow-in-practice"><span class="header-section-number">8.2</span> Forecasting workflow in practice</h2>
<p>If forecasts of this series were required on a recurring annual basis, a structured and repeatable workflow would be essential. Each year would begin by updating the dataset with the latest ABS release, ensuring consistency in definitions, frequency, and transformations. The updated series would then be reviewed visually and statistically to assess changes in trend, seasonality, or variance, supported by tools such as time series plots and STL decomposition.</p>
<p>Rather than reusing a fixed model indefinitely, the data structure would be reassessed annually. ETS and ARIMA models would be re-evaluated using information criteria, residual diagnostics, and recent out-of-sample performance to ensure the selected specification remains appropriate. Once a suitable model is identified, it would be refitted to the full, updated dataset and used to generate forecasts for the following 12 to 24 months, accompanied by 80% and 95% prediction intervals to communicate uncertainty.</p>
<p>Finally, forecast accuracy would be monitored by comparing previous forecasts to realised outcomes using metrics such as RMSE or MAPE. Persistent deterioration in performance would trigger a more thorough reassessment of the modelling approach, while still maintaining a consistent and interpretable forecasting framework. This process balances methodological discipline with flexibility, allowing forecasts to remain relevant as economic conditions evolve.</p>
</section>
</section>
<section id="references" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> References</h1>
<p>Hyndman, R. J., &amp; Athanasopoulos, G. (2021). Forecasting: Principles and practice (3rd ed.). OTexts. <a href="https://otexts.com/fpp3/">https://otexts.com/fpp3/</a></p>
<p>Hadley Wickham, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al.&nbsp;(2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686. <a href="https://cran.r-project.org/web/packages/tidyverse">https://cran.r-project.org/web/packages/tidyverse</a></p>
<p>Rob J Hyndman, Earo Wang (2020). fpp3: Data for “Forecasting: Principles and Practice” (3rd edition) [R package]. <a href="https://CRAN.R-project.org/package=fpp3">https://CRAN.R-project.org/package=fpp3</a></p>
<p>Sam Firke (2023). janitor: Simple tools for examining and cleaning dirty data [R package]. <a href="https://CRAN.R-project.org/package=janitor">https://CRAN.R-project.org/package=janitor</a></p>
<p>Garrett Grolemund, Hadley Wickham (2011). Dates and times made easy with lubridate. Journal of Statistical Software, 40(3), 1–25. <a href="https://cran.r-project.org/web/packages/lubridate">https://cran.r-project.org/web/packages/lubridate</a></p>
<p>Thomas Lin Pedersen (2023). patchwork: The Composer of Plots [R package]. <a href="https://CRAN.R-project.org/package=patchwork">https://CRAN.R-project.org/package=patchwork</a></p>
<p>Matt Cowgill (2024). readabs: Download and Tidy Time Series Data from the Australian Bureau of Statistics (ABS) [R package]. <a href="https://CRAN.R-project.org/package=readabs">https://CRAN.R-project.org/package=readabs</a></p>
<p>Max Kuhn, Davis Vaughan, Romain François, Daniel Falbel, and Jeroen Ooms (2023). yardstick: Tidy Characterizations of Model Performance [R package]. <a href="https://CRAN.R-project.org/package=yardstick">https://CRAN.R-project.org/package=yardstick</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>